import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 920, height: 900 } });
await page.goto('http://localhost:5173/', { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
console.log('920 loaded scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await page.setViewportSize({ width: 390, height: 900 });
await page.waitForTimeout(600);
console.log('390 hot scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await page.screenshot({ path: 'resize-390-hot.png' });
await page.setViewportSize({ width: 640, height: 900 });
await page.waitForTimeout(600);
console.log('640 hot scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await page.screenshot({ path: 'resize-640-hot.png' });
await page.setViewportSize({ width: 920, height: 900 });
await page.waitForTimeout(600);
console.log('920 hot scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await page.screenshot({ path: 'resize-920-hot.png' });
// also test result view hot resize
const btn = page.locator('button:has-text("Ver resultado")').first();
await btn.click();
await page.waitForTimeout(800);
console.log('result loaded');
await page.setViewportSize({ width: 390, height: 900 });
await page.waitForTimeout(600);
console.log('result 390 hot scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await page.screenshot({ path: 'resize-result-390-hot.png' });
await page.setViewportSize({ width: 920, height: 900 });
await page.waitForTimeout(600);
console.log('result 920 hot scrollHeight', await page.evaluate(()=>document.documentElement.scrollHeight));
await browser.close();
console.log('done');
